apiVersion: v1
appVersion: v1.4
description: mall config center
home: https://github.com/gerrywen/spring-cloud-mall/tree/master/mall-config
icon: https://avatars0.githubusercontent.com/u/52062600?s=400&v=4
keywords:
  - mall
  - config
maintainers:
  - email: blog@gerrywen.com
    name: gerrywen
name: mall-config
sources:
  - https://github.com/kubernetes/charts
  - https://github.com/gerrywen/spring-cloud-mall/tree/master/mall-config
version: 0.1.0
