apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-2g
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    -  ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.33.100
    path: /home/prometheus/2g