apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-8g
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  -  ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.33.100
    path: /home/prometheus/8g
