image: "elastic/elasticsearch"
imageTag: "7.8.1"
imagePullPolicy: "IfNotPresent"
podAnnotations: {}
replicas: 1
minimumMasterNodes: 1
esJavaOpts: "-Xmx1g -Xms1g"
resources:
  requests:
    cpu: "100m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "local-storage"
  resources:
    requests:
      storage: 30Gi