apiVersion: v1
appVersion: v1.2
description: mall user
home: https://github.com/gerrywen/spring-cloud-mall
icon: https://avatars0.githubusercontent.com/u/52062600?s=400&v=4
keywords:
  - mall
  - user
maintainers:
  - email: blog@gerrywen.com
    name: gerrywen
name: mall-user
sources:
  - https://github.com/kubernetes/charts
  - https://github.com/gerrywen/spring-cloud-mall
version: 0.1.0
