apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-1g
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  -  ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.33.100
    path: /home/grafana/1g
